spring:
  application:
    name: taxManager

  rabbitmq:
    host: localhost
    port: 5672
    username: calaresedf
    password: microservizi
    listener:
      simple:
        retry:
          enabled: false

  mail:
    host: mail.unimol.it
    port: 587
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://localhost:5432/unimol
    username: unimol
    password: calaresedf

  jpa:
    hibernate:
      ddl-auto: update

  test:
    database:
      replace: NONE

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
  override-with-generic-response: false

microservizi:
  gestioneutenti:
    base-url: http://localhost:23109
  pagopa:
    base-url: http://localhost:23110
  reportistica:
    base-url: http://localhost:23111

jwt:
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1VbY9kO3vlwfXjK1aAfJI9mk64e3lsMJlDulpGJeC7XkvTl8ebmBS9FnD1yKD27pvlRs2WMUIJXDOycgAfti7TQMZUKBBg5ktNQHhpXWiTtf/T4hDa/sIUeZGDtoX3IqriOJIjsjfh/VP61EynFcWdEiAIJhQt798CgQAp4qZZgAwswidwKhib38/cpYheDQSWnKp7j9wiytc4JVkYdQcmUwD6l1GnM6LEXoFm98KwYYI3BmqLdd5uXBH8qG2C/xbhhyNKrhuYoGZ8GmduSmwtsRzCiAxAlosf9M0XJIydjyuCsSj+yS2VhOoFag9hKEUgHBLIXvDJNaSz1O/IOCfQIDAQAB